from schemas.tarea_schema import TareaSchema, TareaConUsuarioSchema
from schemas.usuario_schema import UsuarioSchema, UsuarioLoggedSchema, UsuarioConTareasSchema
from schemas.validate_json import validate_json